### ISSUE TITLE
GET http://localhost:3000/game-service/rounds/db9d9226-30cb-4dd2-acef-736fc548a708 404 (Not Found)

### ISSUE THREAD

**Issue by daehwan2** [code-etc/code-etc-worldcup-frontend#30]
```javascript
const gameCurrentRoundInfo = await axios({
          url: `/game-service/rounds/${gameRoundInfo.data.rounds[0]}`,
          method: "GET",
        });
```

```
Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)
```

현재 이 부분에 404 not found 에러가 발생하는데 이 과정을 해결중이신건가요?

@yunjin-kim

**Comment by daehwan2** [comment]
proxy 서버 설정을 안해줘서 났던 오류.
